### ISSUE TITLE
Attempting to press "update this mod" while in downloaded mods tab crashes

### ISSUE THREAD

**Issue by Teacyn** [Elaviers/GCManager#3] opened 2019-05-01 17:11 UTC
Also, after this happened I found myself unable to re-open the mod manager. I'm not sure if it was opening and then instantly crashing or totally failing to open, but it was certainly something. Deleting the entire contents of the "download" folder I specified allowed me to open the manager again.

**Comment by wataniyob** [comment] 2019-05-02 02:37
Ditto on this issue, except in my case it occurred when updating a single mod on the "Online Mods" tab which I'd previously downloaded.

For me I just needed to delete the mod I attempted to update from the "Downloads" folder and the manager would start up properly.  Otherwise like the OP I would be unable to re-open the manager.  

As some extra info to help with troubleshooting, the updated mod under the "Downloads" folder was empty after the attempted update except for the mod's icon and the following error shows up under the Windows Event Viewer after each failed attempt to re-open the manager:

Event 1026, .NET Runtime
Application: GCManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32, Boolean)
   at System.IO.File.InternalReadAllText(System.String, System.Text.Encoding, Boolean)
   at System.IO.File.ReadAllText(System.String)
   at GCManager.ModListDownloaded.GetMods()
   at GCManager.ModListControl.RefreshList()
   at GCManager.MainWindow..ctor()
   at GCManager.App.StartupEvent(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at GCManager.App.Main()

**Comment by Elaviers** [comment] 2019-05-02 07:06
Thanks for all the info!
The cause of this issue is quite silly...
The job list still has icon.png open when the program tries to delete all of the downloaded mod data.
It'll be fixed in v1.3.5... although in the meantime 1.3.4 will give you nicer errors!

**Comment by Elaviers** [comment] 2019-05-14 00:39
Fixed in 62bb353e1b2aec4f6df0e150d1e7ff9c8610f622

**Closed as completed by Elaviers** 2019-05-14 00:39 UTC
